Error: Nextion script doesn´t stop sometimes
Changed stop of threads to signal handling instead of KeyboardInterrupt
Exception.
Added Exception logging to both scripts